## handling Imbalanced Dataset

1. Up Sampling
2. Down Sampling

In [1]:
import numpy as np
import pandas as pd

#set the random seed for reproduciblity
np.random.seed(123)

#create dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [2]:
n_class_0,n_class_1

(900, 100)

In [3]:
## CREATE MY DATAFRAME WITH IMBALANCED DATASET

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2':np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2':np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

In [4]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [5]:
df.head()

   feature_1  feature_2  target
0  -1.085631   0.551302       0
1   0.997345   0.419589       0
2   0.282978   1.815652       0
3  -1.506295  -0.252750       0
4  -0.578600  -0.292004       0

In [6]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [7]:
## up sampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [9]:
!pip install scikit-learn

Defaulting to user installation because normal site-packages is not writeable
Collecting scikit-learn
  Downloading scikit_learn-1.7.2-cp313-cp313-win_amd64.whl.metadata (11 kB)
Requirement already satisfied: numpy>=1.22.0 in c:\users\91620\appdata\roaming\python\python313\site-packages (from scikit-learn) (2.3.3)
Collecting scipy>=1.8.0 (from scikit-learn)
  Downloading scipy-1.16.3-cp313-cp313-win_amd64.whl.metadata (60 kB)
Collecting joblib>=1.2.0 (from scikit-learn)
  Using cached joblib-1.5.2-py3-none-any.whl.metadata (5.6 kB)
Collecting threadpoolctl>=3.1.0 (from scikit-learn)
  Using cached threadpoolctl-3.6.0-py3-none-any.whl.metadata (13 kB)
Downloading scikit_learn-1.7.2-cp313-cp313-win_amd64.whl (8.7 MB)
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 296.3 kB/s eta 0:00:28
   --- ------------------------------------ 0.8/8.7 MB 428.4 kB/s eta 0:00:19
   --- ------------------------------------ 0.8/8.7 MB 428.4 kB/s eta 0:00:19
   --- ------------------------------------ 0.8/8.7 MB 428.4 kB/s eta 0:00:19
   --- ------------------------------------ 0.8/8.7 MB 428.4 kB/s eta 0:00:19
   ---- ----------------------------------- 1.0/8.7 MB 389.0 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/8.7 MB 389.0 kB/s eta 0:00:20
   ---- ----------------------------------- 1.0/8.7 MB 389.0 kB/s eta 0:00:20
   ------ --------------------------------- 1.3/8.7 MB 414.4 kB/s eta 0:00:18
   ------- -------------------------------- 1.6/8.7 MB 459.5 kB/s eta 0:00:16
   ------- -------------------------------- 1.6/8.7 MB 459.5 kB/s eta 0:00:16
   -------- ------------------------------- 1.8/8.7 MB 497.1 kB/s eta 0:00:14
   -------- ------------------------------- 1.8/8.7 MB 497.1 kB/s eta 0:00:14
   -------- ------------------------------- 1.8/8.7 MB 497.1 kB/s eta 0:00:14
   --------- ------------------------------ 2.1/8.7 MB 477.1 kB/s eta 0:00:14
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ---------- ----------------------------- 2.4/8.7 MB 512.5 kB/s eta 0:00:13
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------ --------------------------- 2.6/8.7 MB 398.8 kB/s eta 0:00:16
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   ------------- -------------------------- 2.9/8.7 MB 337.6 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   -------------- ------------------------- 3.1/8.7 MB 310.0 kB/s eta 0:00:18
   --------------- ------------------------ 3.4/8.7 MB 296.7 kB/s eta 0:00:18
   ---------------- ----------------------- 3.7/8.7 MB 312.4 kB/s eta 0:00:17
   ---------------- ----------------------- 3.7/8.7 MB 312.4 kB/s eta 0:00:17
   ---------------- ----------------------- 3.7/8.7 MB 312.4 kB/s eta 0:00:17
   ------------------ --------------------- 3.9/8.7 MB 320.7 kB/s eta 0:00:15
   ------------------- -------------------- 4.2/8.7 MB 335.7 kB/s eta 0:00:14
   ------------------- -------------------- 4.2/8.7 MB 335.7 kB/s eta 0:00:14
   ------------------- -------------------- 4.2/8.7 MB 335.7 kB/s eta 0:00:14
   ------------------- -------------------- 4.2/8.7 MB 335.7 kB/s eta 0:00:14
   -------------------- ------------------- 4.5/8.7 MB 336.9 kB/s eta 0:00:13
   -------------------- ------------------- 4.5/8.7 MB 336.9 kB/s eta 0:00:13
   --------------------- ------------------ 4.7/8.7 MB 347.2 kB/s eta 0:00:12
   --------------------- ------------------ 4.7/8.7 MB 347.2 kB/s eta 0:00:12
   --------------------- ------------------ 4.7/8.7 MB 347.2 kB/s eta 0:00:12
   ---------------------- ----------------- 5.0/8.7 MB 348.1 kB/s eta 0:00:11
   ---------------------- ----------------- 5.0/8.7 MB 348.1 kB/s eta 0:00:11
   ---------------------- ----------------- 5.0/8.7 MB 348.1 kB/s eta 0:00:11
   ------------------------ --------------- 5.2/8.7 MB 352.9 kB/s eta 0:00:10
   ------------------------- -------------- 5.5/8.7 MB 365.5 kB/s eta 0:00:09
   -------------------------- ------------- 5.8/8.7 MB 378.1 kB/s eta 0:00:08
   --------------------------- ------------ 6.0/8.7 MB 391.7 kB/s eta 0:00:07
   ---------------------------- ----------- 6.3/8.7 MB 400.0 kB/s eta 0:00:07
   ------------------------------ --------- 6.6/8.7 MB 412.2 kB/s eta 0:00:06
   ------------------------------- -------- 6.8/8.7 MB 425.2 kB/s eta 0:00:05
   -------------------------------- ------- 7.1/8.7 MB 436.5 kB/s eta 0:00:04
   -------------------------------- ------- 7.1/8.7 MB 436.5 kB/s eta 0:00:04
   --------------------------------- ------ 7.3/8.7 MB 442.4 kB/s eta 0:00:04
   ---------------------------------- ----- 7.6/8.7 MB 450.9 kB/s eta 0:00:03
   ------------------------------------ --- 7.9/8.7 MB 464.0 kB/s eta 0:00:02
   -------------------------------------- - 8.4/8.7 MB 487.9 kB/s eta 0:00:01
   -------------------------------------- - 8.4/8.7 MB 487.9 kB/s eta 0:00:01
   ---------------------------------------- 8.7/8.7 MB 494.0 kB/s  0:00:17
Using cached joblib-1.5.2-py3-none-any.whl (308 kB)
Downloading scipy-1.16.3-cp313-cp313-win_amd64.whl (38.5 MB)
   ---------------------------------------- 0.0/38.5 MB ? eta -:--:--
   ---------------------------------------- 0.3/38.5 MB ? eta -:--:--
    --------------------------------------- 0.5/38.5 MB 2.6 MB/s eta 0:00:15
    --------------------------------------- 0.8/38.5 MB 2.0 MB/s eta 0:00:19
   - -------------------------------------- 1.0/38.5 MB 1.2 MB/s eta 0:00:31
   - -------------------------------------- 1.3/38.5 MB 1.3 MB/s eta 0:00:29
   - -------------------------------------- 1.6/38.5 MB 1.4 MB/s eta 0:00:26
   -- ------------------------------------- 2.1/38.5 MB 1.5 MB/s eta 0:00:25
   -- ------------------------------------- 2.1/38.5 MB 1.5 MB/s eta 0:00:25
   -- ------------------------------------- 2.4/38.5 MB 1.4 MB/s eta 0:00:27
   -- ------------------------------------- 2.6/38.5 MB 1.3 MB/s eta 0:00:27
   --- ------------------------------------ 3.1/38.5 MB 1.4 MB/s eta 0:00:25
   --- ------------------------------------ 3.4/38.5 MB 1.4 MB/s eta 0:00:25
   --- ------------------------------------ 3.4/38.5 MB 1.4 MB/s eta 0:00:25
   ---- ----------------------------------- 3.9/38.5 MB 1.4 MB/s eta 0:00:26
   ---- ----------------------------------- 4.5/38.5 MB 1.5 MB/s eta 0:00:24
   ---- ----------------------------------- 4.7/38.5 MB 1.5 MB/s eta 0:00:23
   ----- ---------------------------------- 5.0/38.5 MB 1.5 MB/s eta 0:00:23
   ----- ---------------------------------- 5.2/38.5 MB 1.4 MB/s eta 0:00:24
   ----- ---------------------------------- 5.8/38.5 MB 1.5 MB/s eta 0:00:23
   ------ --------------------------------- 6.0/38.5 MB 1.5 MB/s eta 0:00:22
   ------ --------------------------------- 6.6/38.5 MB 1.5 MB/s eta 0:00:21
   ------ --------------------------------- 6.6/38.5 MB 1.5 MB/s eta 0:00:21
   ------- -------------------------------- 6.8/38.5 MB 1.5 MB/s eta 0:00:22
   ------- -------------------------------- 7.3/38.5 MB 1.5 MB/s eta 0:00:21
   -------- ------------------------------- 7.9/38.5 MB 1.5 MB/s eta 0:00:20
   -------- ------------------------------- 8.1/38.5 MB 1.5 MB/s eta 0:00:20
   -------- ------------------------------- 8.1/38.5 MB 1.5 MB/s eta 0:00:20
   -------- ------------------------------- 8.7/38.5 MB 1.5 MB/s eta 0:00:20
   --------- ------------------------------ 8.9/38.5 MB 1.5 MB/s eta 0:00:20
   --------- ------------------------------ 9.4/38.5 MB 1.5 MB/s eta 0:00:19
   --------- ------------------------------ 9.4/38.5 MB 1.5 MB/s eta 0:00:19
   ---------- ----------------------------- 9.7/38.5 MB 1.5 MB/s eta 0:00:20
   ---------- ----------------------------- 10.2/38.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 10.7/38.5 MB 1.5 MB/s eta 0:00:19
   ----------- ---------------------------- 11.0/38.5 MB 1.5 MB/s eta 0:00:18
   ----------- ---------------------------- 11.0/38.5 MB 1.5 MB/s eta 0:00:18
   ----------- ---------------------------- 11.5/38.5 MB 1.5 MB/s eta 0:00:18
   ------------ --------------------------- 12.1/38.5 MB 1.5 MB/s eta 0:00:18
   ------------ --------------------------- 12.3/38.5 MB 1.5 MB/s eta 0:00:17
   ------------- -------------------------- 12.6/38.5 MB 1.6 MB/s eta 0:00:17
   ------------- -------------------------- 12.8/38.5 MB 1.5 MB/s eta 0:00:17
   ------------- -------------------------- 13.4/38.5 MB 1.5 MB/s eta 0:00:17
   -------------- ------------------------- 13.6/38.5 MB 1.5 MB/s eta 0:00:17
   -------------- ------------------------- 13.9/38.5 MB 1.5 MB/s eta 0:00:16
   -------------- ------------------------- 13.9/38.5 MB 1.5 MB/s eta 0:00:16
   -------------- ------------------------- 14.2/38.5 MB 1.5 MB/s eta 0:00:17
   --------------- ------------------------ 14.7/38.5 MB 1.5 MB/s eta 0:00:16
   --------------- ------------------------ 15.2/38.5 MB 1.5 MB/s eta 0:00:16
   ---------------- ----------------------- 15.5/38.5 MB 1.5 MB/s eta 0:00:15
   ---------------- ----------------------- 15.7/38.5 MB 1.5 MB/s eta 0:00:16
   ---------------- ----------------------- 16.0/38.5 MB 1.5 MB/s eta 0:00:15
   ----------------- ---------------------- 16.5/38.5 MB 1.5 MB/s eta 0:00:15
   ----------------- ---------------------- 17.0/38.5 MB 1.6 MB/s eta 0:00:14
   ----------------- ---------------------- 17.0/38.5 MB 1.6 MB/s eta 0:00:14
   ------------------ --------------------- 17.6/38.5 MB 1.5 MB/s eta 0:00:14
   ------------------ --------------------- 17.8/38.5 MB 1.5 MB/s eta 0:00:14
   ------------------- -------------------- 18.4/38.5 MB 1.6 MB/s eta 0:00:13
   ------------------- -------------------- 18.6/38.5 MB 1.6 MB/s eta 0:00:13
   ------------------- -------------------- 18.9/38.5 MB 1.5 MB/s eta 0:00:13
   ------------------- -------------------- 19.1/38.5 MB 1.6 MB/s eta 0:00:13
   -------------------- ------------------- 19.7/38.5 MB 1.6 MB/s eta 0:00:13
   -------------------- ------------------- 20.2/38.5 MB 1.6 MB/s eta 0:00:12
   -------------------- ------------------- 20.2/38.5 MB 1.6 MB/s eta 0:00:12
   --------------------- ------------------ 20.4/38.5 MB 1.6 MB/s eta 0:00:12
   --------------------- ------------------ 21.0/38.5 MB 1.6 MB/s eta 0:00:12
   ---------------------- ----------------- 21.5/38.5 MB 1.6 MB/s eta 0:00:11
   ---------------------- ----------------- 22.0/38.5 MB 1.6 MB/s eta 0:00:11
   ---------------------- ----------------- 22.0/38.5 MB 1.6 MB/s eta 0:00:11
   ----------------------- ---------------- 22.3/38.5 MB 1.6 MB/s eta 0:00:11
   ----------------------- ---------------- 22.5/38.5 MB 1.6 MB/s eta 0:00:11
   ----------------------- ---------------- 22.8/38.5 MB 1.6 MB/s eta 0:00:11
   ------------------------ --------------- 23.3/38.5 MB 1.6 MB/s eta 0:00:10
   ------------------------ --------------- 23.6/38.5 MB 1.6 MB/s eta 0:00:10
   ------------------------ --------------- 23.9/38.5 MB 1.6 MB/s eta 0:00:10
   ------------------------- -------------- 24.4/38.5 MB 1.6 MB/s eta 0:00:10
   ------------------------- -------------- 24.6/38.5 MB 1.6 MB/s eta 0:00:09
   ------------------------- -------------- 24.9/38.5 MB 1.6 MB/s eta 0:00:09
   -------------------------- ------------- 25.2/38.5 MB 1.6 MB/s eta 0:00:09
   -------------------------- ------------- 25.7/38.5 MB 1.6 MB/s eta 0:00:09
   --------------------------- ------------ 26.2/38.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 26.5/38.5 MB 1.6 MB/s eta 0:00:08
   --------------------------- ------------ 26.7/38.5 MB 1.6 MB/s eta 0:00:08
   ---------------------------- ----------- 27.0/38.5 MB 1.6 MB/s eta 0:00:08
   ---------------------------- ----------- 27.5/38.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 28.0/38.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 28.3/38.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 28.3/38.5 MB 1.6 MB/s eta 0:00:07
   ----------------------------- ---------- 28.6/38.5 MB 1.6 MB/s eta 0:00:07
   ------------------------------ --------- 29.1/38.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 29.6/38.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------ --------- 29.6/38.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 30.1/38.5 MB 1.6 MB/s eta 0:00:06
   ------------------------------- -------- 30.7/38.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 30.9/38.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 31.2/38.5 MB 1.6 MB/s eta 0:00:05
   -------------------------------- ------- 31.5/38.5 MB 1.6 MB/s eta 0:00:05
   --------------------------------- ------ 32.0/38.5 MB 1.6 MB/s eta 0:00:05
   --------------------------------- ------ 32.2/38.5 MB 1.6 MB/s eta 0:00:04
   --------------------------------- ------ 32.5/38.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 32.8/38.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 33.0/38.5 MB 1.6 MB/s eta 0:00:04
   ---------------------------------- ----- 33.6/38.5 MB 1.6 MB/s eta 0:00:04
   ----------------------------------- ---- 34.1/38.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 34.3/38.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 34.3/38.5 MB 1.6 MB/s eta 0:00:03
   ----------------------------------- ---- 34.6/38.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 35.1/38.5 MB 1.6 MB/s eta 0:00:03
   ------------------------------------ --- 35.4/38.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 35.7/38.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 35.9/38.5 MB 1.6 MB/s eta 0:00:02
   ------------------------------------- -- 36.4/38.5 MB 1.6 MB/s eta 0:00:02
   -------------------------------------- - 37.0/38.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 37.2/38.5 MB 1.6 MB/s eta 0:00:01
   -------------------------------------- - 37.2/38.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  37.7/38.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------  38.3/38.5 MB 1.6 MB/s eta 0:00:01
   ---------------------------------------- 38.5/38.5 MB 1.6 MB/s  0:00:24
Using cached threadpoolctl-3.6.0-py3-none-any.whl (18 kB)
Installing collected packages: threadpoolctl, scipy, joblib, scikit-learn

   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]
   ---------- ----------------------------- 1/4 [scipy]

In [11]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority,replace=True, #Sample with replacement
         n_samples=len(df_majority),
         random_state=42)

In [12]:
df_minority_upsampled.shape

(900, 3)

In [13]:
df_minority_upsampled.head()

     feature_1  feature_2  target
951   1.125854   1.843917       1
992   2.196570   1.397425       1
914   1.932170   2.998053       1
971   2.272825   3.034197       1
960   2.870056   1.550485       1

In [15]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [16]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down sampling

In [17]:

import numpy as np
import pandas as pd

#set the random seed for reproduciblity
np.random.seed(123)

#create dataframe with two classes
n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

class_0 = pd.DataFrame({
    'feature_1':np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2':np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature_1':np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2':np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

#check class distribution
print(df['target'].value_counts())

target
0    900
1    100
Name: count, dtype: int64

In [18]:
## down sampling
df_minority=df[df['target']==1]
df_majority=df[df['target']==0]

In [20]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority,replace=False, #we want to reduce
         n_samples=len(df_minority),
         random_state=42)

In [22]:
df_majority_downsampled.shape

(100, 3)

In [23]:
df_downsampled=pd.concat([df_minority,df_majority_downsampled])

In [24]:
df_downsampled.target.value_counts()

target
1    100
0    100
Name: count, dtype: int64

In [1]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
n_class_0_ratio = 0.8
n_class_0 = int(n_samples * n_class_0_ratio)
n_class_1 = n_samples - n_class_0

In [10]:
class_0 = pd.DataFrame({
    'feature 1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature 2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' : [0] * n_class_0
})

class_1 = pd.DataFrame({
    'feature 1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature 2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1
})

In [11]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)
df['target'].value_counts()

target
0    800
1    200
Name: count, dtype: int64

In [12]:
df_maj = df[df['target']==0]
df_min = df[df['target']==1]

In [ ]:
from sklearn.utils import resample
df_min_upsampled = resample(df_min, replace=True,random_state=42, n_samples=len(df_maj))

In [14]:
df_min_upsampled.head()

     feature 1  feature 2  target
902   1.707439   2.674931       1
979   1.616703   2.084903       1
892   1.813643   1.927428       1
814   3.846091   2.850840       1
906   0.885715   3.723456       1

In [16]:
df_min_upsampled.shape

(800, 3)

In [21]:
df_upsampled=pd.concat([df_maj,df_min_upsampled])
df_upsampled.target.value_counts()

target
0    800
1    800
Name: count, dtype: int64