## Pandas
Data manipulation library widely used for data analysis and cleaning.

Types of data structure
1. series :- one dimension Array
2. Dataframe :- two dimension array

In [1]:
import pandas as pd

In [4]:
data = [1,2,3,4,5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [8]:
# create series from dictionary

data ={'a':1, 'b':2, 'c':3}
series_dic = pd.Series(data)
print(series_dic)

data = [10,20,30]
index = ['a','b','c']
print(pd.Series(data, index))

a    1
b    2
c    3
dtype: int64
a    10
b    20
c    30
dtype: int64

In [9]:
# Data Frame
data = {
    'Name' : ['Krish', 'Ankit'],
    'Age' : [30, 20],
    'city' : ['mumbai', 'jabalpur']
}
df = pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age      city
0  Krish   30    mumbai
1  Ankit   20  jabalpur
<class 'pandas.core.frame.DataFrame'>

In [28]:
# Accessing data from dataframe
data['Name']
type(data['Name'])

list

In [37]:
data=[
    {'Name':'Krish','Age':32,'City':'Bangalore'},
    {'Name':'John','Age':34,'City':'Bangalore'},
    {'Name':'Bappy','Age':32,'City':'Bangalore'},
    {'Name':'JAck','Age':32,'City':'Bangalore'}
    
]
df=pd.DataFrame(data)
print(df)
print(type(df))

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore
<class 'pandas.core.frame.DataFrame'>

In [ ]:
df
df.loc[0] #row wise
#df.iloc[1] # column wise

Name        Krish
Age            32
City    Bangalore
Name: 0, dtype: object

In [ ]:
##Accesing a specified element
df.at[1, 'Age']
#df.at[2, 'Name']
df.iat[2,2]

'Bangalore'

In [49]:
# Data manipulation with dataframe
df['salary'] = [10, 40, 50, 60]
df

    Name  Age       City  salary
0  Krish   32  Bangalore      10
1   John   34  Bangalore      40
2  Bappy   32  Bangalore      50
3   JAck   32  Bangalore      60

In [53]:
df.drop('salary', axis=1) #temporary delete
df
df.drop('salary', axis=1, inplace=True) #permament delete
df

    Name  Age       City
0  Krish   32  Bangalore
1   John   34  Bangalore
2  Bappy   32  Bangalore
3   JAck   32  Bangalore

In [54]:
df['Age'] = df['Age']+1
df

    Name  Age       City
0  Krish   33  Bangalore
1   John   35  Bangalore
2  Bappy   33  Bangalore
3   JAck   33  Bangalore

In [10]:
import numpy as np
np.array(df)

array([['Krish', 30, 'mumbai'],
       ['Ankit', 20, 'jabalpur']], dtype=object)

In [56]:
df = pd.read_csv('sales_data.csv')
#print(df.head(5))
df.head(5)
#print(df.tail(5))

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [57]:
print("data types", df.dtypes)

data types Transaction ID        int64
Date                 object
Product Category     object
Product Name         object
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region               object
Payment Method       object
dtype: object

In [60]:
#statistical analysis
#print("statistical summary: ", df.describe())
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [29]:
df['Product Name']
df.iloc[0]
#type(df['Product Name'])

Transaction ID              10001
Date                   2024-01-01
Product Category      Electronics
Product Name        iPhone 14 Pro
Units Sold                      2
Unit Price                 999.99
Total Revenue             1999.98
Region              North America
Payment Method        Credit Card
Name: 0, dtype: object